apiVersion: apps/v1
kind: Deployment
metadata:
  name: ivia-runtime-db
spec:
  selector:
    matchLabels:
      app: ivia-runtime-db
  replicas: 1
  template:
    metadata:
      name: ivia-runtime-db
      labels:
        app: ivia-runtime-db
    spec:
      serviceAccountName: ivia-anyuid
      securityContext:
        fsGroup: 70
      volumes:
        - name: ivia-runtime-db
          persistentVolumeClaim:
            claimName: ivia-runtime-db-pvc
      containers:
        - name: ivia-runtime-db
          image: icr.io/isva/verify-access-postgresql:10.0.9.0
          ports:
            - containerPort: 5432
              name: postgresql
          # Environment definition. In a production environment we
          # would not enable UNSECURE mode and the credential information
          # would be stored in a secret
          env:
            - name: POSTGRES_UNSECURE
              value: "true"
            - name: POSTGRES_USER
              value: ivia
            - name: POSTGRES_PASSWORD
              value: passw0rd1
            - name: POSTGRES_DB
              value: ivia
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: ivia-runtime-db
