apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ivia-config-pvc-h2
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: PATCHED_BY_KUSTOMIZE
  resources:
    requests:
      storage: 2Gi
