apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ibm-verify-operands
spec:
  generators:
  - list:
      elements:
        - name: config
          namespace: ibm-verify
          sync-wave: "200"
        #- name: wrp
        #  namespace: ibm-verify
        #  sync-wave: "200"
  template:
    metadata:
      name: '{{name}}'
      labels:
        group: applications
      annotations:
        argocd.argoproj.io/sync-wave: '{{sync-wave}}'
    spec:
      project: ibm-verify-operands
      source:
        path: 'env/odf/operands/verify-access/{{name}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
