apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ivia-automated-config-job.yaml
  - ivia-automated-config-job-role.yaml
  - ivia-automated-config-job-rb.yaml
  - ivia-automated-config-job-sa.yaml
