kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-verify-argo-role
rules:
  - verbs:
      - '*'
    apiGroups:
      - ibm.com
    resources:
      - ibmsecurityverifyaccesses
