container:
  k8s_deployments:
    namespace: "ibm-verify"
    runtime: 
      - "ivia-runtime"
    webseal:
      - "via-wrpi"
  admin_cfg:
    session_timeout: 720
  account_management:
    users:
    - name: "cfgsvc"
      operation: "update"
      password: !secret ibm-verify/ivia-secrets:cfgsvc-passwd
  management_authorization:
    authorization_enforcement: True
    roles:
    - operation: "update"
      name: "Configuration Service"
      users:
      - name: "cfgsvc"
        type: "local"
      features:
      - name: "shared_volume"
        access: "w"
  ssl_certificates:
  - name: "lmi_trust_store"
    signer_certificates:
    - "/tmp/pki/postgresql.pem"
    - "/tmp/pki/openldap.pem"
  - name: "rt_profile_keys"
    signer_certificates:
    - "/tmp/pki/postgresql.pem"
  cluster:
    runtime_database:
      host: "ivia-runtime-db.ibm-verify.svc.cluster.local"
      port: 5432
      type: "postgresql"
      user: "ivia"
      password: !secret ibm-verify/ivia-secrets:postgres-passwd
      ssl: False
      db_name: "ivia"
  activation: #Activation codes
    webseal: !secret ibm-verify/ivia-secrets:base-code
    access_control: !secret ibm-verify/ivia-secrets:aac-code
    federation: !secret ibm-verify/ivia-secrets:fed-code
webseal:
  runtime:
    policy_server: "local"
    admin_user: sec_master
    #admin_user: !secret ibm-verify/ivia-secrets:sec-user
    admin_password: !secret ibm-verify/ivia-secrets:sec-passwd
    admin_cert_lifetime: 1460
    domain: "Default"
    user_registry: "ldap"
    ldap:
      host: "openldap.ibm-verify.svc"
      port: 389
      dn: !secret ibm-verify/ivia-secrets:ldap-binddn
      dn_password: !secret ibm-verify/ivia-secrets:ldap-passwd
  reverse_proxy:
    - name: "default"
      host: "ivia-config.ibm-verify.svc.cluster.local"
      http:
        enabled: "no"
      https:
        enabled: "yes"
      domain: "Default"
      ldap:
        ssl_yn: "no"
        port: 389
      aac_configuration:
        hostname: "localhost"
        port: 443
        runtime:
          user: !secret ibm-verify/ivia-secrets:rtime-user
          password: !secret ibm-verify/ivia-secrets:rtime-passwd
        junction: "/mga"
        reuse_acls: True
        reuse_certs: True
        mapping_rules:
        # Can also use directory, see example here: https://github.com/lachlan-ibm/ibmvia_autoconf/blob/8d4175f6fcf87f1da3710a9c43e80a2299a21def/examples/mmfa_demo/mmfa_config.yaml#L87C5-L87C23
        - type: InfoMap
          files:
            - mapping-rules/rule1.js
            - mapping-rules/rule2.js